// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAhRLVYDN2Ql5rhb66VaxzesQcEYp-LsBg',
//     appId: '1:47857378119:android:aa84a8fdaa14da5a42e262',
//     messagingSenderId: '47857378119',
//     projectId: 'cocoa-rehab',
//     storageBucket: 'cocoa-rehab.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCaSXoDlIrySMUn2Zq-oGR1oaQ5MWc8QUM',
//     appId: '1:47857378119:ios:ab0a54d8f0b24c3742e262',
//     messagingSenderId: '47857378119',
//     projectId: 'cocoa-rehab',
//     storageBucket: 'cocoa-rehab.appspot.com',
//     androidClientId: '47857378119-0ffn7cc1ojim0ki5mel2u3ofiem4ggls.apps.googleusercontent.com',
//     iosClientId: '47857378119-4de8gbd33r826fi6h2ktqb9tb4btkad9.apps.googleusercontent.com',
//     iosBundleId: 'com.afarinick.kumad.cocoamonitor',
//   );
// }
